# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170522_1404')
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='series.Series'),
        ),
    ]
