* Requests
** Sent  
** Want
* Email templates
** Messages
**** Stories
Hi! My name is Ray, I have built a website [fictionhub.io](http://fictionhub.io) - I want it to become a great place for writers to share their stories, find the audience, and discover awesome fiction.
     
I have read your stories on /r/WritingPrompts, and now I'm a huge fan =) I think they are really briliant, exactly the kind of stuff I would love to see in our community, so I wanted to ask if you would agree to add them to fictionhub.

Your stories will be featured on the front page, and I expect that they'll be read by at least 12-15 thousand people during the next few months. Your profile will link to your [website/subreddit], and send you some readres and subscribers =)
 
I think our users will really enjoy reading your stories, and I would be extremely happy if you would agree to share them on fictionhub. Please let me know what you think!
**** Story
Hi! My name is Ray, I have built a website [fictionhub.io](http://fictionhub.io) - I want it to become a great place for writers to share their stories, find the audience, and discover awesome fiction.
     
I have discovered your [story about life's difficulty level](https://www.reddit.com/r/WritingPrompts/comments/4cmk5a/wp_you_just_got_fired_youre_pretty_sure_your/d1jkux5) on /r/WritingPrompts, I think it's really briliant, and I would really love to see it on fictionhub, so I want to ask if you [could give me permission  to post] [would like to publish] it there.

It will be featured on the front page, and I expect that it'll be read by at least 8-12 thousand people during the next few months. Your profile  will have a link to /r/MatiWrites, and send you some readers and subscribers =)

I think our users would really enjoy reading your story, and I would be extremely happy if you would agree to share it on fictionhub. Please let me know what you think! =)

**** Thank you

Oh, this is awesome, thank you very much!

I have added your story [here](http://fictionhub.io/story/current-setting-very-hard).

If you want, you can login into your account with username "mati" and a password "$qEd%Dsb4cJBhmt" (you can change it in [preferences](http://fictionhub.io/preferences/)).


If you'd like to change anything - let me know =)

* Reddit
** General Writing  
/r/Screenwriting
/r/Writing
/r/WritingPrompts
/r/WritingPrompts
/r/WritersGroup
/r/WriterMotivation
/r/write/
/r/rational


/r/Writing
/r/Screenwriting
/r/writers
/r/sciencefiction
/r/fantasy
/r/shortstories


** Share Stories General:
/r/sciencefiction
/r/Scifi  
/r/fantasy
/r/shortstories

** Fanfiction communities:
/r/pokemon



* Tags
how to,write,writing, creative writing,fiction,storytelling,story,plot,
screenwriting,screenplay,short,film,
class,course,lessons,advice,learning,resources,tutorials,lectures,
write a screenplay,screenwriting course,become a screenwiter,
short, flash,
write jokes,jokes,comedy,stand up,humor,sketch,
cartoon, animation,

fiction, science fiction, fantasy, short story, comedy

tumblr:
fiction, science fiction, fantasy, short story, comedy
writing, fanfiction, scifi, story, storytelling

twitter:
#fiction #webfiction #shortstory
#fiction #sciencefiction #scifi #webfiction #shortstory
#fantasy #comedy
#writingprompts

medium:
Fiction(28k)
Short Story(33k)
writing creative writing creativity storytelling
* Info
150 W. 85th Street
New York
10024
646 718
628 for SF

685 Great Northern Way
Vancouver, BC V5T 0C6
V5T 0C6
Canada
