# Generated by Django 2.0.dev20170211211108 on 2017-02-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=256)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('post_type', models.CharField(blank=True, choices=[('article', 'Article'), ('book', 'Book'), ('video', 'Video')], default='video', max_length=64)),
                ('post_level', models.CharField(blank=True, choices=[('all', 'All'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='all', max_length=64)),
                ('post_price', models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=64)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tags.Tag')),
            ],
        ),
    ]
