# Generated by Django 2.0.dev20170211211108 on 2017-02-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_level',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
