# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170522_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
