# Generated by Django 2.0.dev20170211211108 on 2017-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170216_0025'),
        ('profiles', '0002_user_upvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to='comments.Comment'),
        ),
    ]
