# Generated by Django 2.0.dev20170211211108 on 2017-02-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_comments_upvoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
