# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='free_chapters',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='series',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
