# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
