# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170614_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_email',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
