# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path),
        ),
    ]
