# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170615_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='ref',
            new_name='src',
        ),
        migrations.AddField(
            model_name='user',
            name='src',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
